artifact_uri: file:///users/aramello/deeplearning/mlruns/1/82d5f741ff5f446cb18000e5e355f9c7/artifacts
end_time: 1616127267270
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 82d5f741ff5f446cb18000e5e355f9c7
run_uuid: 82d5f741ff5f446cb18000e5e355f9c7
source_name: ''
source_type: 4
source_version: ''
start_time: 1616125680292
status: 3
tags: []
user_id: aramello
