artifact_uri: file:///users/aramello/deeplearning/mlruns/1/7ae725339f2340e9aece2661064cf30e/artifacts
end_time: 1616264767853
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 7ae725339f2340e9aece2661064cf30e
run_uuid: 7ae725339f2340e9aece2661064cf30e
source_name: ''
source_type: 4
source_version: ''
start_time: 1616262761601
status: 3
tags: []
user_id: aramello
