artifact_uri: file:///users/aramello/deeplearning/mlruns/1/e2ca84ce8e704a26a37a61bf1c9b23f6/artifacts
end_time: 1616266738254
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: e2ca84ce8e704a26a37a61bf1c9b23f6
run_uuid: e2ca84ce8e704a26a37a61bf1c9b23f6
source_name: ''
source_type: 4
source_version: ''
start_time: 1616265054652
status: 3
tags: []
user_id: aramello
