artifact_uri: file:///users/aramello/deeplearning/mlruns/1/23ebde03beb1493d8bb501079f671af1/artifacts
end_time: 1616259938564
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 23ebde03beb1493d8bb501079f671af1
run_uuid: 23ebde03beb1493d8bb501079f671af1
source_name: ''
source_type: 4
source_version: ''
start_time: 1616258246580
status: 3
tags: []
user_id: aramello
